import { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Play, Sparkles, RefreshCw, Clock, Calendar, CheckCircle, AlertTriangle } from 'lucide-react';
import axios from '../api/axios';

export default function Planner() {
  const [schedule, setSchedule] = useState(null);
  const [availableHours, setAvailableHours] = useState(4);
  const [startTimeInput, setStartTimeInput] = useState('09:00');
  const [isGenerating, setIsGenerating] = useState(false);
  const [mood, setMood] = useState('Neutral');

  useEffect(() => {
    fetchSchedule();
  }, []);

  const fetchSchedule = async () => {
    try {
      const res = await axios.get('/schedule');
      setSchedule(res.data);
    } catch (error) {
      console.error(error);
    }
  };

  const handleGeneratePlan = async () => {
    setIsGenerating(true);
    try {
      const res = await axios.post('/generate-plan', {
        availableHours,
        mood,
        startTime: startTimeInput
      });
      setSchedule(res.data);
    } catch (error) {
      console.error(error);
    } finally {
      setIsGenerating(false);
    }
  };


  const handleSimulateChaos = async () => {
    setIsGenerating(true);
    try {
      const res = await axios.post('/reschedule');
      setSchedule(res.data);
    } catch (error) {
      console.error(error);
    } finally {
      setIsGenerating(false);
    }
  };

  const getBlockStyle = (type, missed) => {
    if (missed) return 'border-tertiary/30 bg-tertiary/10 text-tertiary shadow-[0_0_15px_rgba(255,179,173,0.1)]';
    switch (type) {
      case 'Study': return 'border-primary/30 bg-primary/10 text-primary-200';
      case 'Break': return 'border-secondary/30 bg-secondary/10 text-secondary-200';
      case 'Revision': return 'border-white/10 bg-white/5 text-gray-200';
      default: return 'border-white/5 bg-surface-container/50';
    }
  };

  return (
    <div className="max-w-5xl mx-auto space-y-12 pb-20 relative">
      {/* Header */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-end gap-6">
        <div className="space-y-2">
          <h1 className="text-5xl font-black tracking-tight">
            Study <span className="text-primary text-glow">Planner</span>
          </h1>
          <p className="text-gray-400 text-lg">Hyper-optimized study sessions generated by AI.</p>
        </div>
        
        <button 
          onClick={handleSimulateChaos}
          className="flex items-center gap-2 px-6 py-3 bg-tertiary/10 text-tertiary hover:bg-tertiary/20 border border-tertiary/30 rounded-2xl transition-all text-sm font-bold uppercase tracking-widest"
        >
          <RefreshCw className="w-4 h-4" /> Simulate Chaos
        </button>
      </div>

      {/* Configuration Hub */}
      <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
        <div className="lg:col-span-3 glass-card p-8 flex flex-col md:flex-row items-center gap-8 border-l-4 border-secondary">
          <div className="flex-1 w-full space-y-4">
            <div className="flex justify-between items-center">
              <label className="text-xs font-black text-gray-500 uppercase tracking-widest">Available Bandwidth</label>
              <span className="text-secondary font-black bg-secondary/10 px-3 py-1 rounded-lg">{availableHours} Hours</span>
            </div>
            <input 
              type="range" min="1" max="12" step="0.5"
              value={availableHours}
              onChange={e => setAvailableHours(parseFloat(e.target.value))}
              className="w-full h-2 bg-surface-container rounded-lg appearance-none cursor-pointer accent-secondary"
            />
          </div>

          <div className="h-12 w-px bg-white/5 hidden md:block"></div>

          <div className="w-full md:w-32 space-y-4 relative z-10">
            <label className="text-xs font-black text-gray-500 uppercase tracking-widest block">Start Time</label>
            <input 
              type="time"
              value={startTimeInput}
              onChange={e => {
                console.log('Time Change:', e.target.value);
                setStartTimeInput(e.target.value);
              }}
              style={{ colorScheme: 'dark' }}
              className="w-full bg-surface-container border border-white/10 rounded-xl px-3 py-3 text-sm focus:outline-none focus:border-secondary transition-all font-bold text-white cursor-pointer"
            />
          </div>
          
          <div className="h-12 w-px bg-white/5 hidden md:block"></div>
          
          <button 
            onClick={handleGeneratePlan}
            disabled={isGenerating}
            className="w-full md:w-auto px-10 py-4 bg-primary text-background font-black rounded-2xl flex items-center justify-center gap-3 transition-all hover:scale-105 active:scale-95 glow-primary disabled:opacity-50"
          >
            {isGenerating ? <RefreshCw className="w-5 h-5 animate-spin" /> : <Sparkles className="w-5 h-5" />}
            GENERATE
          </button>
        </div>
        
        <div className="glass-card p-6 flex flex-col justify-center items-center text-center">
          <p className="text-[10px] font-black text-gray-500 uppercase tracking-widest mb-2">Efficiency Rating</p>
          <p className="text-4xl font-black text-white">A+</p>
        </div>
      </div>

      {/* Timeline Section */}
      <div className="glass-card p-1">
        {!schedule || !schedule.blocks || schedule.blocks.length === 0 ? (
          <div className="text-center py-24 px-6">
            <div className="w-20 h-20 bg-surface-container rounded-3xl flex items-center justify-center mx-auto mb-6 border border-white/5 shadow-inner">
              <Calendar className="w-10 h-10 text-gray-700" />
            </div>
            <h3 className="text-2xl font-bold text-gray-300 mb-2">No active sequence detected</h3>
            <p className="text-gray-500 max-w-sm mx-auto">Set your available hours and initialize the focus engine to generate your roadmap.</p>
          </div>
        ) : (
          <div className="p-8 space-y-8">
            <div className="flex items-center justify-between border-b border-white/5 pb-6">
              <div className="flex items-center gap-4">
                <div className="p-3 bg-primary/10 rounded-xl">
                  <CheckCircle className="w-6 h-6 text-primary" />
                </div>
                <div>
                  <h3 className="font-black text-xl uppercase tracking-tight">Active Protocol</h3>
                  <p className="text-xs text-gray-500 font-bold uppercase tracking-widest">{schedule.blocks.length} Neural Blocks Scheduled</p>
                </div>
              </div>
              <div className="text-right">
                <p className="text-3xl font-black text-white leading-none">{schedule.totalStudyTime}</p>
                <p className="text-[10px] text-gray-500 font-black uppercase tracking-widest">Minutes Total</p>
              </div>
            </div>

            <div className="relative border-l-2 border-white/5 ml-4 space-y-8 py-4">
              {schedule.blocks.map((block, i) => (
                <motion.div 
                  key={i}
                  initial={{ opacity: 0, x: -20 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: i * 0.1 }}
                  className="relative pl-10"
                >
                  <div className={`absolute -left-[9px] top-2 w-4 h-4 rounded-full border-4 border-background ${block.missed ? 'bg-tertiary shadow-[0_0_10px_rgba(255,179,173,0.5)]' : 'bg-primary shadow-[0_0_10px_rgba(221,183,255,0.5)]'}`}></div>
                  
                  <div className={`p-6 rounded-3xl border ${getBlockStyle(block.type, block.missed)} transition-all hover:scale-[1.02] cursor-default group overflow-hidden relative`}>
                    {block.missed && (
                      <div className="absolute top-0 right-0 bg-tertiary text-background text-[10px] font-black px-3 py-1 rounded-bl-xl uppercase tracking-tighter">
                        Interrupted
                      </div>
                    )}
                    
                    <div className="flex justify-between items-start mb-4">
                      <div>
                        <h4 className={`text-2xl font-black tracking-tight ${block.missed ? 'text-tertiary' : 'text-white'}`}>{block.title}</h4>
                        <div className="flex items-center gap-3 mt-1">
                          <span className="text-[10px] font-black uppercase tracking-widest opacity-60 flex items-center gap-1">
                            <Clock className="w-3 h-3" /> {block.startTime} - {block.endTime}
                          </span>
                        </div>
                      </div>
                      <div className="bg-black/20 px-4 py-2 rounded-2xl backdrop-blur-sm border border-white/5">
                        <p className="text-xs font-black uppercase tracking-widest">{block.duration}m</p>
                      </div>
                    </div>
                    
                    <div className="flex justify-between items-center">
                      <div className="flex items-center gap-2">
                         <span className={`px-3 py-1 rounded-lg text-[10px] font-black uppercase tracking-widest ${block.type === 'Study' ? 'bg-primary/20 text-primary' : block.type === 'Break' ? 'bg-secondary/20 text-secondary' : 'bg-white/10 text-gray-400'}`}>
                           {block.type} Session
                         </span>
                      </div>
                      
                      {block.type === 'Study' && !block.missed && (
                        <button className="p-3 bg-white/10 hover:bg-white/20 rounded-full transition-all">
                          <Play className="w-4 h-4" />
                        </button>
                      )}
                    </div>
                  </div>
                </motion.div>
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

